[package]
name = "tuidemo"
version = "0.1.0"
description = "nothing"
authors = ["harjeb"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
csv = "1.3"
regex = "1"
